# Module for toggling human in the loop during topic modelling
# Enables the option to edit the topics generated by the LLM,
#   before they are assigned to texts

#### 1 UI

human_in_the_loop_toggle_ui <- function(id) {
  ns <- NS(id)
  uiOutput(ns("ui_toggle"))
}


#### 2 Server

human_in_the_loop_toggle_server <- function(
  id,
  processing,
  mode,
  lang = reactiveVal(
    shiny.i18n::Translator$new(
      translation_json_path = "language/language.json"
    )
  )
) {
  moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns

      toggle <- reactiveVal(FALSE)

      # Only show the toggle when the mode is "Onderwerpextractie"
      output$ui_toggle <- renderUI({
        req(mode() == "Onderwerpextractie")
        tagList(
          shinyjs::useShinyjs(),
          bslib::card(
            class = "card",
            card_header(lang$t("Human-in-the-loop")),
            card_body(
              # Toggle for inter-rater reliability
              p(
                lang$t("Zelf onderwerpen bewerken?"),
                class = "mb-2 text-center"
              ),
              div(
                class = "d-flex justify-content-center",
                shinyWidgets::radioGroupButtons(
                  ns("toggle"),
                  NULL,
                  choices = c(lang$t("Nee"), lang$t("Ja")),
                  selected = lang$t("Nee"),
                  size = "sm"
                )
              )
            )
          )
        )
      })

      # Observe the toggle input and update the reactive value
      observeEvent(input$toggle, {
        toggle(input$toggle == lang$t("Ja"))
      })

      # Disable when processing
      observeEvent(
        processing(),
        {
          shinyjs::toggleState(
            "toggle",
            condition = !processing()
          )
        },
        ignoreInit = TRUE
      )

      return(toggle)
    }
  )
}


#### 3 Example/development usage

if (FALSE) {
  library(shiny)
  library(shinyjs)
  library(shinyWidgets)

  ui <- bslib::page(
    useShinyjs(),
    css_js_head(),
    human_in_the_loop_toggle_ui("human_in_the_loop")
  )

  server <- function(input, output, session) {
    processing <- reactiveVal(FALSE)
    mode <- reactiveVal("Onderwerpextractie") # Simulating the mode selection

    human_in_the_loop_toggle_server("human_in_the_loop", processing, mode)
  }

  shinyApp(ui, server)
}
