# Module for toggling human in the loop during topic modelling
# Enables the option to edit the topics generated by the LLM,
#   before they are assigned to texts
#
# This module uses the reusable yes_no_toggle_card component

# 1 UI ---------------------------------------------------------------
human_in_the_loop_toggle_ui <- function(id) {
  yes_no_toggle_card_ui(id)
}


# 2 Server ---------------------------------------------------------
human_in_the_loop_toggle_server <- function(
  id,
  processing,
  mode,
  lang = default_lang()
) {
  # Call the reusable component - note: passing raw strings, component will translate
  yes_no_toggle_card_server(
    id = id,
    title = "Human-in-the-loop",
    tooltip_text = "Indien je dit aanzet, kun je de de onderwerpen die het taalmodel heeft geïdentificeerd in de teksten bekijken en bewerken. Dit kan je dan doen dan voordat de onderwerpen worden toegewezen aan de teksten. Je kan bijvoorbeeld zelf bepaalde onderwerpen toevoegen, verwijderen, samenvoegen, of uitsplitsen.",
    question_text = "Zelf onderwerpen bewerken?",
    default_value = FALSE,
    show_when = reactive(mode() == "Onderwerpextractie"),
    translate_texts = TRUE, # Tell component to translate the texts reactively
    processing = processing,
    lang = lang
  )
}


# 3 Example/development usage --------------------------------------
if (FALSE) {
  library(shiny)
  library(shinyjs)
  library(shinyWidgets)

  ui <- bslib::page(
    useShinyjs(),
    css_js_head(),
    human_in_the_loop_toggle_ui("human_in_the_loop")
  )

  server <- function(input, output, session) {
    processing <- reactiveVal(FALSE)
    mode <- reactiveVal("Onderwerpextractie")

    human_in_the_loop_toggle_server("human_in_the_loop", processing, mode)
  }

  shinyApp(ui, server)
}
