---
title: "Scoring with LLM"
output: 
  html_document:
    theme:
      version: 5
      bootswatch: lux
params:
  result_list: !r list(df = data.frame(result = c(1), text = c("Tekst A")), irr = list(estimate = setNames(27.58, "mean difference"), statistic = setNames(8.975326, "t"), p.value = 6.416833e-12, parameter = setNames(49, "df"), conf.low = 21.40484, conf.high = 33.75516, method = "Paired t-test", alternative = "two.sided", llm_mean = 23.33, llm_sd = 5.72, user_mean = 36.7824, user_sd = 7.23), sensitivity_sentence = "Met een steekproefgrootte van (...).")

---

```{r include=FALSE, error=TRUE}
rl <- params$result_list
```

## Method

`r nrow(rl$df)` texts were analyzed with an LLM (model: `r rl$model`),
where the LLM was asked to provide a score (1-100) indicating
how well a text fits the characteristic '*`r rl$scoring_characteristic`*'.

Each text was presented separately to the LLM.

```{r echo=FALSE, results='asis', error=TRUE}
if (!is.null(rl$irr)) {
  cat(paste0(
    "### Reliability\n",
    "The inter-rater reliability between the language model and a human rater was calculated.",
    " A random sample of ",
    rl$irr$subjects, " texts was taken.",
    "A paired t-test was used to compare the scores given by the language model with those given by the human rater.",
    " The mean difference between the scores is ",
    round(rl$irr$estimate, 2), " (95% CI [",
    round(rl$irr$conf.low, 2), ", ",
    round(rl$irr$conf.high, 2), "];",
    " mean language model = ", round(rl$irr$llm_mean, 2),
    " [sd = ", round(rl$irr$llm_sd, 2), "];",
    " mean human rater = ", round(rl$irr$user_mean, 2),
    " [sd = ", round(rl$irr$user_sd, 2), "]).",
    " This is a  ",
    dplyr::case_when(
      rl$irr$p.value < 0.05 ~ "significant",
      TRUE ~ "not significant"
    ),
    " difference (t(", rl$irr$parameter, ") = ",
    round(rl$irr$statistic, 3), ", p = ", round(rl$irr$p.value, 3), ") ",
    " and can be interpreted as ",
    dplyr::case_when(
      rl$irr$p.value >= 0.05 ~ "an agreement between the scores of the language model and the human rater",
      rl$irr$llm_mean > rl$irr$user_mean ~ "an overestimation of the scores by the language model",
      rl$irr$llm_mean < rl$irr$user_mean ~ "an underestimation of the scores by the language model",
      TRUE ~ "?"
    ), ".\n\n", rl$irr$sensitivity_sentence
  ))
}
```

## Results

### Statistics

Below table shows statistics of the given scores.

```{r results='asis', echo=FALSE, error=TRUE}
rl$df |>
  dplyr::summarise(
    Mean = round(mean(result), 2),
    `Standard deviation` = round(sd(result), 2),
    Minimum = min(result),
    Maximum = max(result),
    Median = median(result)
  ) |>
  DT::datatable(
    rownames = FALSE,
    extensions = 'Buttons',
    options = list(
      pageLength = 10,
      lengthMenu = c(10, 25, 50, 100),
      scrollX = TRUE,
      scrollY = "400px",
      scrollCollapse = TRUE,
      dom = 'Bfrtip',
      buttons = list('excel', 'csv', 'pdf', 'print')
    )
  )
```

### Per text

Below table shows the scores per text.

```{r results='asis', echo=FALSE, error=TRUE}
rl$df |>
  dplyr::select(result, text) |>
  dplyr::rename(Text = text, Score = result) |>
  dplyr::arrange(dplyr::desc(Score)) |>
  DT::datatable(
    extensions = 'Buttons',
    options = list(
      rownnames = FALSE,
      pageLength = 10,
      lengthMenu = c(10, 25, 50, 100),
      scrollX = TRUE,
      scrollY = "400px",
      scrollCollapse = TRUE,
      dom = 'Bfrtip',
      buttons = list('excel', 'csv', 'pdf', 'print')
    )
  )
```
 
```{r footer, echo=FALSE, results='asis', error=TRUE}
htmltools::tags$footer(
  style = "text-align:center; font-size: 0.8em; color: #888; margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee;",
  htmltools::HTML(paste0(
    "This analysis was automatically generated by an app developed by ",
    "<a href='https://www.kennispunttwente.nl' target='_blank'>Kennispunt Twente</a> in collaboration with GGD Twente.<br>",
    "Visit the <a href='https://github.com/kennispunttwente/tekstanalyse_met_llm' target='_blank'>GitHub-repository</a> for more information.",
    "<br>",
    "<br>",
    format(Sys.Date(), "%Y-%m-%d")
  ))
)
```
